# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: MIT
"""Console utils."""

BLACK_BACKGROUND_COLOR = 40
BLUE_BACKGROUND_COLOR = 44
GREY_BACKGROUND_COLOR = 47
ANSITERM_ROWS_SIZE = 30
ANSITERM_COLS_SIZE = 80
